project_id = "wjmrvzohrqwasrcoaban"

[functions.chatbot-ai]
verify_jwt = false

[functions.moderate-content]
verify_jwt = false
 
 [functions.fetch-news]
 verify_jwt = false

[functions.ai-market-analysis]
verify_jwt = false

[functions.fetch-stock-data]
verify_jwt = false

[functions.equity-research-ai]
verify_jwt = false

[functions.fetch-article-content]
verify_jwt = false
